version: 1.0.{build}

image: Visual Studio 2015

environment:
  cpptango_download_base: https://github.com/tango-controls/cppTango/releases/download/
  cpptango_version: 9.3.3
  boost_download_base: https://github.com/tango-controls/boost-ci/releases/download/
  boost_version: 1.70.0
  matrix:
    - platform: win32
      ARCH: win32-msvc9
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 9 2008"
      MSVCVERSION: v90
      MSVCYEAR: "vs2008"
      MSVCABR: "9"
      VC_VER: 9.0
      PYTHONPATH: c:\Python27\
      ARCH_PY: win32-msvc9-py27
      PY_VER: 27
    - platform: x64
      ARCH: x64-msvc9
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 9 2008 Win64"
      MSVCVERSION: v90
      MSVCYEAR: "vs2008"
      MSVCABR: "9"
      VC_VER: 9.0
      PYTHONPATH: c:\Python27-x64\
      ARCH_PY: x64-msvc9-py27
      PY_VER: 27

    - platform: win32
      ARCH: win32-msvc14
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 14 2015"
      MSVCVERSION: v140
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python36\
      ARCH_PY: win32-msvc14-py36
      PY_VER: 36
    - platform: x64
      ARCH: x64-msvc14
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
      MSVCVERSION: v140
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python36-x64\
      ARCH_PY: x64-msvc14-py36
      PY_VER: 36

    - platform: win32
      ARCH: win32-msvc14
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 14 2015"
      MSVCVERSION: v140
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python37\
      ARCH_PY: win32-msvc14-py37
      PY_VER: 37

    - platform: x64
      ARCH: x64-msvc14
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
      MSVCVERSION: v140
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python37-x64\
      ARCH_PY: x64-msvc14-py37
      PY_VER: 37

init:
  # go to hell Xamarin (see http://help.appveyor.com/discussions/problems/4569)
  - del "C:\Program Files (x86)\MSBuild\4.0\Microsoft.Common.Targets\ImportAfter\Xamarin.Common.targets"
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - del "C:\Program Files (x86)\MSBuild\12.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

  # Tango
  - cmd: cd "C:\projects\"
  - cmd: md libtango
  - cmd: cd "C:\projects\"
  - if %platform%==win32 appveyor DownloadFile %cpptango_download_base%/%cpptango_version%/libtango_%cpptango_version%_%MSVCVERSION%_x86.zip
  - if %platform%==x64 appveyor DownloadFile %cpptango_download_base%/%cpptango_version%/libtango_%cpptango_version%_%MSVCVERSION%_x64.zip
  - cmd: if %platform%==win32 7z -y x libtango_%cpptango_version%_%MSVCVERSION%_x86.zip -oC:\projects\libtango\
  - cmd: if %platform%==x64 7z -y x libtango_%cpptango_version%_%MSVCVERSION%_x64.zip -oC:\projects\libtango\

  # boost
  - cmd: cd "C:\projects\"
  - appveyor DownloadFile %boost_download_base%/%boost_version%/boost-python-%boost_version%_%ARCH%_py%PY_VER%.zip
  - cmd: 7z -y x boost-python-%boost_version%_%ARCH%_py%PY_VER%.zip -oC:\projects\

  #VS2008 patch
  - cmd: cd "C:\projects\"
  - cmd: appveyor DownloadFile https://github.com/menpo/condaci/raw/master/vs2008_patch.zip
  - cmd: 7z -y x vs2008_patch.zip -oC:\projects\vs2008_patch\
  - cmd: if %ARCH%==x64-msvc9 call C:\projects\vs2008_patch\setup_x64.bat
  - cmd: if %ARCH%==x32-msvc9 call C:\projects\vs2008_patch\setup_x86.bat
  - cmd: if %ARCH%==x64-msvc9 copy "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64\vcvarsamd64.bat"
  - cmd: cd "C:\projects\pytango"

install:
  # Setting Visual Compiler
  - cmd: cd "C:\projects\"
  - cmd: if %ARCH%==win32-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==win32-msvc9 set path=C:\Windows\Microsoft.NET\Framework\v4.0.30319;%path%
  - cmd: if %ARCH%==x64-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat"
  - cmd: if %ARCH%==win32-msvc14 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==x64-msvc14 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cmd: echo "Generator='%CMAKE_GENERATOR%'"
  - cmd: echo "Platform='%Platform%'"
  - cmd: set PYTHONPATH=%PYTHONPATH%
  - "%PYTHONPATH%/Scripts/pip.exe install nose wheel numpy"
  # Tango Server
  - cmd: cd "C:\projects\pytango"
  - cmd: dir
  - cmd: set BOOST_ROOT=c:/projects/Boost/include/boost-1_70
  - cmd: set BOOST_LIBS=c:/projects/Boost/lib
  - cmd: if %ARCH%==win32-msvc9 set TANGO_PATH=C:/projects/libtango/libtango_%cpptango_version%_v90_x86/
  - cmd: if %ARCH%==x64-msvc9 set TANGO_PATH=C:/projects/libtango/libtango_%cpptango_version%_v90_x64/
  - cmd: if %ARCH%==win32-msvc14 set TANGO_PATH=C:/projects/libtango/libtango_%cpptango_version%_v140_x86/
  - cmd: if %ARCH%==x64-msvc14 set TANGO_PATH=C:/projects/libtango/libtango_%cpptango_version%_v140_x64/
  - cmd: if %ARCH_PY%==win32-msvc9-py27 cmake -G "%CMAKE_GENERATOR%" . -DPY_27=TRUE
  - cmd: if %ARCH_PY%==x64-msvc9-py27 cmake -G "%CMAKE_GENERATOR%" . -DPY_27=TRUE
  - cmd: if %ARCH_PY%==win32-msvc14-py36 cmake -G "%CMAKE_GENERATOR%" . -DPY_36=TRUE
  - cmd: if %ARCH_PY%==x64-msvc14-py36 cmake -G "%CMAKE_GENERATOR%" . -DPY_36=TRUE
  - cmd: if %ARCH_PY%==win32-msvc14-py37 cmake -G "%CMAKE_GENERATOR%" . -DPY_37=TRUE
  - cmd: if %ARCH_PY%==x64-msvc14-py37 cmake -G "%CMAKE_GENERATOR%" . -DPY_37=TRUE

clone_folder: C:\projects\pytango

build:
  parallel: true
  verbosity: minimal
  
build_script:
  - cmd: cd C:/projects/pytango 
  - cmake --build ./ -j 4 --config Release


after_build:
  - cmd: cd C:/projects/pytango/dist
  - cmd: dir
  - cmd: cd C:/projects/pytango 
  #copying artifacts
  - cmd: move .\dist\pytango*.exe C:/projects/pytango
  - cmd: move .\dist\pytango*.whl C:/projects/pytango


on_failure:
  #RDP for failure
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  #RDP for finish
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: ./*.exe
  - path: ./*.whl
